### ISSUE TITLE
Searching a PL Number

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#160] opened 2019-12-12 15:16 UTC
Raised by James
**Describe the bug**
Not all PL numbers seem to be searchable on the site: This PL is for dexamethasone, which does appear to be an active MA on EMC, although I can’t check it on the MHRA site. 

**Expected behavior**
A result for the searched PL number should be returned

**Screenshots**
![image](https://user-images.githubusercontent.com/58432596/70724349-5c095400-1cf2-11ea-9469-2a1d97650d79.png)

**Additional context**

**Comment by SteveLindsay461** [comment] 2019-12-12 15:37
James also checked  and the PL is granted on Sentinel but the PL does not appear on the old MHRA website either

**Comment by m-doughty** [comment] 2019-12-12 17:17
This is essentially caused by the exported data not containing the PL number as a field. My thoughts are that if we attempt to extract the PL number for each SPC/PIL from the file name during the import process and store it either in the keywords metadata or in its own new searchable field, we can probably fix this for ~97% of cases.

**Comment by m-doughty** [comment] 2019-12-13 14:02
Closing this because #192 will resolve it.

**Closed by m-doughty** 2019-12-13 14:02 UTC
Labels: cli tools :hammer_and_wrench:, poor data :hankey:
