### ISSUE TITLE
PARs - Upload new PAR

### ISSUE THREAD

**Issue by sgrowe** [MHRA/products#767] opened 2020-05-06 13:48 UTC
### User want
As a Medical Writer in the licensing team I would like to upload a new PAR document to products.mhra.gov.uk

### Technical acceptance criteria
After submitting a new version of the document the:
- [ ] The PDF is stored in blob storage after upload
- [ ] Azure search service is updated if necessary

### Customer acceptance criteria
- [ ] Medical writers can enter the relevant metadata about the document (such as the product name, active substances and PL/NR/THR number)
- [ ] Medical writers can upload the new document
- [ ] After submitting the user is shown a summary of what they've submitted
- [ ] The new document is available on the products.mhra.gov.uk site

**Comment by rjkerrison** [comment] 2020-05-06 14:22
Duplicate of #375.

**Closed by rjkerrison** 2020-05-06 14:22 UTC
Labels: EPIC - PARs process
