### ISSUE TITLE
PDF File name - When Saving to a local drive

### ISSUE THREAD

**Issue by SteveLindsay461** [MHRA/products#158] opened 2019-12-12 15:00 UTC
**Describe the bug**
When saving a PDF to local drive the file name is a alpha numeric string and  not a very useful file name – can this not match the file name from that which is opened?

Can the Filename  match the file name from that which is opened?
![image](https://user-images.githubusercontent.com/58432596/70723055-31b69700-1cf0-11ea-8c15-71d5bc70ae72.png)

**Comment by DimplePatel** [comment] 2019-12-12 15:17
Refers to this https://github.com/MHRA/products/issues/38

**Comment by m-doughty** [comment] 2019-12-12 15:27
Duplicate of #38?

**Closed by m-doughty** 2019-12-12 15:27 UTC
