### ISSUE TITLE
Learning modules - Summary of licensed indications of antipsychotics for adults doesn't exist

### ISSUE THREAD

**Issue by DimplePatel** [MHRA/products#182] opened 2019-12-13 10:08 UTC
**Describe the bug**
Summary of licensed indications of antipsychotics for adults link takes user to a 404 error

**To Reproduce**
1) Click the hyperlink on this page https://mhracpddev.z33.web.core.windows.net/antipsychotics/CON155606_40 and the user is shown a 404 error
2) https://mhracpddev.z33.web.core.windows.net/antipsychotics/CON155606_2 it's also referenced here in the introduction

**Expected behavior**
The current MHRA site isn't loading for me so i can't reference that right now. I assume we are missing a page of content here 

**Screenshots**

**Additional context**

**Comment by craiga** [comment] 2019-12-13 13:52
I think this is a duplicate of https://github.com/MHRA/products/issues/187

**Closed** 2019-12-16 09:19 UTC
Labels: learning modules 🎓
